### ISSUE TITLE
Ability to use hexcode in General Tab

### ISSUE THREAD

**Issue by chrishoage** [aziz/tmTheme-Editor#157]
I can't seem to figure out out to input hex codes in the General tab, the native color picker is the only way to specify a color and does not offer the ability to use a hexcode. 

Could there be a flyout similar to how it works on the Scopes tab?

**Comment by aziz** [comment]
You're right. It all because the native color pickers were not a good choice and we need to move to a JS based one where you can actually type hex or rgb colors. In the mean time I want to revamp the way we're managing general settings. A lot of features like adding and removing rules are missing right now.  I just need to find some free time to work on it.  PRs are appreciated.

**Comment by aziz** [comment]
Fixed in 0.10.0
